### ISSUE TITLE
hunter-agent function list

### ISSUE THREAD

**Issue by moooofly** [moooofly/hunter-agent#1]
## Core Features

- [x] The role of hunter-agent:
    - [x] From the perspective of opencensus exporter, it is a grpc server.
    - [x] From the perspective of kafka broker, it is a kafka producer.
- [x] Prometheus metrics support.
    - [x] [docker/go-metrics](https://github.com/docker/go-metrics)
    - [x] [prometheus/client_golang](https://github.com/prometheus/client_golang)
- [x] Communication method support:
    - [x] Unix Domain Socket
    - [x] Tcp Socket
- [x] Flow control
    - [x] a basic flow control by channel buffer size.
    - [ ] fulfill flow-control channel length dynamic updating ([issue#8](https://github.com/moooofly/hunter-agent/issues/8))
    - [ ] more complicated flow-control mechanism ([issue#9](https://github.com/moooofly/hunter-agent/issues/9))
- [x] Complicated signal process.
    - [x] Configuration reload by **SIGHUP**.
    - [x] Dump stacks of all goroutines by **SIGUSR1**.
    - [x] Ignore **SIGPIPE**.
    - [x] Call custom `cleanup` function, then terminate process by **SIGINT**/**SIGTERM**.
    - [x] Cause an exit without cleanup, with a goroutine dump preceding exit by **SIGQUIT**.
- [ ] *Add more here...*

## Optional Features

- [x] glide support
- [ ] run as daemon
    - [ ] by systemd
    - [ ] by [sevlyar/go-daemon](https://github.com/sevlyar/go-daemon)
    - [ ] by [fiorix/go-daemon](https://github.com/fiorix/go-daemon)
- [ ] Kafka connection issues:
    - [ ] auth
    - [ ] SSL
- [ ] Control plane
    - [ ] Pass specific requests (whitelist).
    - [ ] Block specific requests (blacklist).
    - [ ] Rewrite specific requests.
- [ ] Keepalive probe and/or Healthy check.
- [ ] Run integration test locally by docker-compose.
- [ ] A CLI client to interact with hunter-agent.
- [ ] add docker-entrypoint.sh support. ([issues#4](https://github.com/moooofly/hunter-agent/issues/4))
- [ ] Port use:
    - The listen port used by grpc server.
    - The random port used by kafka producer.
- [ ] *Add more here...*

**Comment by moooofly** [comment]
# Daemon or not Daemon, is a question

`hunter-agent` does not daemonize on its own. For production usage, **it is recommended to launch in a process supervisor, and drop privileges as appropriate**.

Examples of supervisors include: [daemontools](http://cr.yp.to/daemontools.html), [runit](http://smarden.org/runit/), [upstart](http://upstart.ubuntu.com/), [launchd](http://www.launchd.info/), [systemd](https://www.freedesktop.org/wiki/Software/systemd/), and many more.

For the reasoning behind lack of daemonization, see [daemontools/why](http://cr.yp.to/daemontools/faq/create.html#why). In addition, the code is much simpler because of it.

other: 《[golang 应用的 daemon 问题](https://github.com/moooofly/MarkSomethingDownLLS/blob/master/golang%20%E5%BA%94%E7%94%A8%E7%9A%84%20daemon%20%E9%97%AE%E9%A2%98.md)》 -- private
